[rocketchat.myrocketchat]

#Url is your incoming webhook url as specified in rocketchat
#Read #https://rocket.chat/docs/administrator-guides/integrations/#how-to-create-a-new-incoming-webhook
#See administration - integrations - new integration - incoming webhook
WebhookURL="${ROCKETCHAT_WEBHOOK_URL}"

#Address to listen on for outgoing webhook requests from rocketchat.
#See administration - integrations - new integration - outgoing webhook
WebhookBindAddress="${ROCKETCHAT_WEBHOOK_BIND_ADDRESS}"

Nick="${ROCKETCHAT_NICK}"
RemoteNickFormat="${ROCKETCHAT_REMOTE_NICK_FORMAT}"

[matrix.mymatrix]

#Server is your homeserver (eg https://matrix.org)
Server="${MATRIX_SERVER}"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
#Messages sent from this user will not be relayed to avoid loops.
Login="${MATRIX_LOGIN}"
Password="${MATRIX_PASSWORD}"

RemoteNickFormat="${MATRIX_REMOTE_NICK_FORMAT}"

#Whether to send the homeserver suffix. eg ":matrix.org" in @username:matrix.org
#to other bridges, or only send "username".(true only sends username)
#OPTIONAL (default false)
NoHomeServerSuffix=false

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="rocketchat.myrocketchat"
channel="${ROCKETCHAT_CHANNEL}"

[[gateway.inout]]
account="matrix.mymatrix"
channel="${MATRIX_CHANNEL}"